### ISSUE TITLE
molang folder not detected when doing insertions in deeper level folders

### ISSUE THREAD

**Issue by BigChungus21220** [IceCraft-Studio/Insert-Molang-File-VSC-Ext#1]
This extension fails to find the molang folder when used on files located multiple layers deep.
For example trying to insert a molang file into, features/some_folder/some_file will give the error
"Molang folder can't be found within current behavior/resource pack!"

**Comment by PavelDobCZ23** [comment]
@BigChungus21220 Could you send me a .zip file containing the root folder of your behavior pack as well as the feature files you try to import into and the molang folder with its contents? You can remove the contents of the files, just keep the directory structure and file names the exact same so I can do some debugging on it.

**Comment by BigChungus21220** [comment]
[Custom Biome Template.zip](https://github.com/IceCraft-Studio/Insert-Molang-File-VSC-Ext/files/13261039/Custom.Biome.Template.zip)

**Comment by PavelDobCZ23** [comment]
@BigChungus21220 Thank you. I will be able to work on it tomorrow. Seems like the original thing with `bp` and similar keywords inside the folder name might be causing the issue, you can try to include that in the folder name, but that shouldn't cause issues. I will definitely look into this.

**Comment by PavelDobCZ23** [comment]
@BigChungus21220 UPDATE: I have identified the problem and will fix it in a few days. Basically your subfolder is called "biomes" and that confuses the system to make it think the root of the pack is where your "biomes" subfolder is, which is the "features" folder and that's wrong. I need to rewrite the logic that finds the folders. Again, thanks for your report!

**Comment by PavelDobCZ23** [comment]
@BigChungus21220 Version 2.3.1 of the extension was just released and the issue was fixed. Thanks for using my extension and have a great day!
